apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tuerme-von-hanoi
  name: tuerme-von-hanoi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tuerme-von-hanoi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tuerme-von-hanoi
    spec:
      containers:
        - image: tuerme-von-hanoi:local
            name: tuerme-von-hanoi
            imagePullPolicy: Never
            resources: { }
            volumeMounts:
              - mountPath: /test-pd
                name: test-volume
            volumes:
              - name: test-volume
                hostPath:
                  # directory location on host
                  path: /home/kevin/data
                  # this field is optional
                  type: Directory
        status: { }



