apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
        - image: tuerme-von-hanoi:local
          name: tuerme-von-hanoi
          imagePullPolicy: Never
          resources: { }
          volumeMounts:
            - mountPath: /test-pd
              name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /home/kevin/data
            # this field is optional
            type: Directory